<a href="https://colab.research.google.com/github/MuhammadFarhan96/My-DL-Journey/blob/main/sentiment_analysis_simplernn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
len(tokenizer.word_index)

17

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [10]:
from keras.utils import pad_sequences
from keras.layers import Embedding
from keras.models import Sequential
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [11]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile('adam','accuracy')

In [13]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 670ms/step
[[[ 0.00094417  0.0152761 ]
  [ 0.02669463  0.01173743]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]]

 [[ 0.02669463  0.01173743]
  [ 0.02669463  0.01173743]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]]

 [[ 0.00867575  0.03611134]
  [ 0.00867575  0.03611134]
  [ 0.04336913 -0.02008116]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]]

 [[-0.0355431  -0.03878089]
  [ 0.0015127  -0.01313188]
  [-0.0355431  -0.03878089]
  [ 0.02669463  0.01173743]
  [-0.0355431  -0.03878089]]

 [[ 0.04652759  0.04909507]
  [ 0.00958295  0.01249855]
  [-0.04676489  0.02297444]
  [-0.04425578 -0.04320538]
  [-0.0010673  -0.00565647]]

 [[ 0.02063042 -0.02507663]
  [ 0.02063042 -0.02507663]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.00565647]]

 [[ 0.04827999  0.04591712]
  [ 0.04827999  0.04591712]
  [-0.0010673  -0.00565647]
  [-0.0010673  -0.0056564

In [20]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [21]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [22]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [23]:
X_train.shape

(25000, 50)

In [26]:
model = Sequential()
model.add(Embedding(1000, 2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - acc: 0.5572 - loss: 0.6729 - val_acc: 0.7154 - val_loss: 0.5602
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.7391 - loss: 0.5328 - val_acc: 0.7582 - val_loss: 0.5066
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.7680 - loss: 0.4900 - val_acc: 0.7661 - val_loss: 0.4949
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.7752 - loss: 0.4809 - val_acc: 0.7766 - val_loss: 0.4832
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.7890 - loss: 0.4571 - val_acc: 0.7662 - val_loss: 0.4938
